# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and deploy to QA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'qa'
        options:
          - qa
          - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./powerimo-secret-server/
        push: true
        tags: |
          powerimo/powerimo-secret-backend:test
          powerimo/powerimo-secret-backend:test2

    - name: Logout from Docker Hub
      run: docker logout

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: qa

    steps:
      - name: Copy script to SSH server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .github/bash/deploy-server.sh
          remote: ~/bin/deploy-powerimo-secret-server.sh
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey : ${{ secrets.DEPLOY_USER_KEY }}
          port: ${{ secrets.SSH_PORT }}
      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_USER_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x ~/bin/deploy-powerimo-secret-server.sh
            ~/bin/deploy-powerimo-secret-server.sh
